<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // Falls Kategorien noch nicht existieren
        if (Category::count() === 0) {
            $this->call(CategorySeeder::class);
        }

        // Kategorien abrufen als Name→ID Mapping
        $categories = Category::all()->keyBy('slug');

        // Rezepte nach Kategorie gruppiert
        $recipesByCategory = [
            'vorspeise' => [
                [
                    'name' => 'Bruschetta mit Tomaten und Feta',
                    'status' => 'published',
                    'punchline' => 'Italienischer Klassiker',
                    'description' => 'Geröstetes Brot mit Tomaten, Knoblauch und Basilikum und Petersilie.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 15,
                    'preparation_instructions' => 'Brot rösten, Tomaten schneiden, alles anrichten.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Tomatensuppe',
                    'status' => 'published',
                    'punchline' => 'Ein wärmender Start in den Abend',
                    'description' => 'Cremige Suppe mit frischen Tomaten und Kräutern.',
                    'difficulty' => 'mittel',
                    'rating' => 4,
                    'preparation_time' => 25,
                    'preparation_instructions' => 'Zwiebeln anschwitzen, Tomaten pürieren, würzen.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Grüner Spargel mit Speck',
                    'status' => 'published',
                    'punchline' => 'Nur im Frühling',
                    'description' => 'Super leckerer Spargel mit Speck.',
                    'difficulty' => 'mittel',
                    'rating' => 4,
                    'preparation_time' => 25,
                    'preparation_instructions' => 'Grünen Spargel kurz blanchieren, anschließend in kaltem Wasser kurz abschrecken. Dadurch behält der Spargel seine schöne, grüne Farbe und bleibt knackig.',
                    'is_veggy' => false,
                ],
            ],

            'hauptgericht' => [
                [
                    'name' => 'Ramen Suppe',
                    'status' => 'published',
                    'punchline' => 'Wärmend und herzhaft',
                    'description' => 'Japanische Nudelsuppe mit Brühe, Fleisch und Gemüse.',
                    'difficulty' => 'schwer',
                    'rating' => 5,
                    'preparation_time' => 90,
                    'preparation_instructions' => 'Brühe lange köcheln lassen, Nudeln und Toppings hinzufügen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Fischstäbchen mit Kartoffeln, Spinat und Ei',
                    'status' => 'published',
                    'punchline' => 'Hausmannskost',
                    'description' => 'Kartoffeln und Spinat, Fischstäbchen und Eier.',
                    'difficulty' => 'einfach',
                    'rating' => 4,
                    'preparation_time' => 30,
                    'preparation_instructions' => 'Kartoffeln kochen, Spinat schneiden, Fischstäbchen kochen, Ei dazu - fertig.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Spaghetti Carbonara',
                    'status' => 'published',
                    'punchline' => 'Klassisch italienisch',
                    'description' => 'Pasta mit Speck, Ei und Parmesan.',
                    'difficulty' => 'mittel',
                    'rating' => 5,
                    'preparation_time' => 20,
                    'preparation_instructions' => 'Pasta kochen, Speck anbraten, Eier-Parmesan-Mix hinzufügen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Spaghetti Bolognese',
                    'status' => 'published',
                    'punchline' => 'Klassisch italienisch',
                    'description' => 'Pasta mit Bolognese-Sauce und Parmesan.',
                    'difficulty' => 'mittel',
                    'rating' => 5,
                    'preparation_time' => 45,
                    'preparation_instructions' => 'Hackfleisch scharf anbraten, mit Rotwein ablöschen und weiter köcheln lassen. Dann Milch dazu geben und einkochen.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Lasagne',
                    'status' => 'published',
                    'punchline' => 'Klassisch italienisch',
                    'description' => 'Flache Nudeln mit Bolognese-Sauce, Bechamel und Parmesan.',
                    'difficulty' => 'mittel',
                    'rating' => 5,
                    'preparation_time' => 45,
                    'preparation_instructions' => 'Hackfleisch scharf anbraten, mit Rotwein ablöschen und weiter köcheln lassen. Dann Milch dazu geben und einkochen.',
                    'is_veggy' => true,
                ],
            ],

            'nachtisch' => [
                [
                    'name' => 'Pancakes',
                    'status' => 'published',
                    'punchline' => 'Fluffig und süß',
                    'description' => 'Amerikanische Pfannkuchen mit Ahornsirup.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 20,
                    'preparation_instructions' => 'Teig anrühren, ausbacken und servieren.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Kaiserschmarrn',
                    'status' => 'published',
                    'punchline' => 'Fluffig und süß',
                    'description' => 'Fluffiger Kaiserschmarrn, mit Ahornsirup.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 20,
                    'preparation_instructions' => 'Teig anrühren, ausbacken und servieren.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Tiramisu',
                    'status' => 'published',
                    'punchline' => 'Italienisches Dessert',
                    'description' => 'Schichtdessert mit Mascarpone und Espresso.',
                    'difficulty' => 'mittel',
                    'rating' => 5,
                    'preparation_time' => 30,
                    'preparation_instructions' => 'Biskuits tränken, Schichten aufbauen, kühlen.',
                    'is_veggy' => true,
                ],
            ],

            'snack' => [
                [
                    'name' => 'Avocado Toast',
                    'status' => 'published',
                    'punchline' => 'Schnell und lecker',
                    'description' => 'Geröstetes Brot mit Avocado, Zitrone und Chili.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 10,
                    'preparation_instructions' => 'Brot toasten, Avocado zerdrücken, anrichten.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Feigen im Speckmantel',
                    'status' => 'published',
                    'punchline' => 'Leckere Vorspeise',
                    'description' => 'Schnell vorbereitet, einfach angerichtet.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 10,
                    'preparation_instructions' => 'Feigen mit Speck einrollen und im Backofen oder Heißluftofen für 10-15 Minuten backen.',
                    'is_veggy' => true,
                ],
            ],

            'cocktail' => [
                [
                    'name' => 'Alabama Slammer',
                    'status' => 'published',
                    'punchline' => 'Southern Comfort Cocktail',
                    'description' => 'Spannender Cocktail mit Southern Comfort und Orangensaft.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Glas mit 2 Eiswürfeln und Dekoration vorbereiten. Alle Zutaten kräftig shaken und ins Glas geben.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Aperol Fizz',
                    'status' => 'published',
                    'punchline' => 'Longdrink mit Aperol und Soda',
                    'description' => 'Erfrischender Longdrink mit Aperol.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten bis auf das Sodawasser shaken und ins Glas abstrainen. Anschließend das Sodawasser hinzufügen. Zur Dekoration eine Zitrone und eine Kirsche ins Glas geben.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Apricot Flower',
                    'status' => 'published',
                    'punchline' => 'Erfrischend und fruchtig',
                    'description' => 'Apricot Brandy mit Orangensaft und anderen Säften - lecker.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas abstrainen. Zur Dekoration eine Orange mit Kirsche am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Bloody Mary',
                    'status' => 'published',
                    'punchline' => 'Der Drink für den Tag danach',
                    'description' => 'Aufbauend nach dem Kater - garantiert.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Ein Shakerglas vorkühlen und das Schmelzwasser vorher abgießen. Dann alle Zutaten ins Shakerglas geben, Salz, Pfeffer, Selleriesalz, Tabasco und Worcestershire-Sauce und den Spritzer Zitrone dazu geben. Anschließend alles verrühren (nicht shaken, Vorsicht schäumt).',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Boston Cocktail',
                    'status' => 'published',
                    'punchline' => 'Unbekannt aber gut',
                    'description' => 'Aufbauend nach dem Kater - garantiert.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zur Dekoration eine Zitrone und eine Kirsche am Stick ins Glas geben.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Bounty',
                    'status' => 'published',
                    'punchline' => 'Riegel mit Alkohol in flüssiger Form',
                    'description' => 'Lecker mit Kokos und Créme de Cacao.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zur Dekoration mit Kokosraspeln und Kakaopulver bestreuen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Brandy Alexander',
                    'status' => 'published',
                    'punchline' => 'Brandy Veterano in Bestform',
                    'description' => 'Brandy Veterano, Créme de Cacao Braun mit Sahne und Muskat. Richtig lecker.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zum Finish mit frisch geraspelter Muskatnuss bestreuen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Flying Kangaroo',
                    'status' => 'published',
                    'punchline' => 'Wie Pina Colada mit Orangenflair',
                    'description' => 'In etwa wie eine Pina Colada, allerdings mit einem Schuss Galiano und Orange.',
                    'difficulty' => 'leicht',
                    'rating' => 4,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zur Dekoration eine Orange und eine Kirsche am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Gimlet (Gin)',
                    'status' => 'published',
                    'punchline' => 'Muss man mögen',
                    'description' => 'Schmeckt nicht jeder Zunge, aber wenn der dann mal läuft, ist er ein Klassiker.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zur Dekoration eine Limette am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Gimlet (Wodka)',
                    'status' => 'published',
                    'punchline' => 'Muss man mögen',
                    'description' => 'Die Wodka Variante des Gimlets.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zur Dekoration eine Limette am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Gin Fizz',
                    'status' => 'published',
                    'punchline' => 'Longdrink-Klassiker',
                    'description' => 'Erfrischer Longdrink mit ganz eigenem Geschmack.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zur Dekoration eine Zitrone und eine Kirsche ins Glas geben.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Golden Cadillac',
                    'status' => 'published',
                    'punchline' => 'Orangiger Longdrink-Klassiker',
                    'description' => 'Longdrink einem Touch mit Orange.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten shaken und ins Glas geben. Zur Dekoration eine Orange und eine Kirsche am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Harvey Wallbanger',
                    'status' => 'published',
                    'punchline' => 'Wodka-O mit Galiano',
                    'description' => 'Wodka-O mit Galiano abgerundet. Nicht ganz so langweilig wie Wodka-O alleine.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten ins Glas geben. Zur Dekoration eine Orange und eine Kirsche ins Glas geben.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Mexicana',
                    'status' => 'published',
                    'punchline' => 'Tequila mit Zitrone, Limette und Grenadine',
                    'description' => 'Sehr zitronig und fruchtig.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten ins Glas geben. Zur Dekoration eine Orange und eine Kirsche ins Glas geben.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Nutty Colada',
                    'status' => 'published',
                    'punchline' => 'Amaretto mit Kokos und Sahne',
                    'description' => 'Sehr lecker, für süße Zungen geeignet.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten ins Glas geben. Zur Dekoration eine Orange und eine Kirsche am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Pina Colada',
                    'status' => 'published',
                    'punchline' => 'Rum mit Kokos und Sahne',
                    'description' => 'Sehr lecker, für karibischen Flair.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten ins Glas geben. Zur Dekoration eine Ananas und eine Kirsche am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Planter\'s Punch',
                    'status' => 'published',
                    'punchline' => 'Fruchtiger Klassiker',
                    'description' => 'Fruchtig, lecker, bekannt.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten (zuerst den Alkohol, anschließend die Säfte) ins Glas geben. Zur Dekoration eine Ananas und eine Kirsche am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Screaming Orgasm',
                    'status' => 'published',
                    'punchline' => 'Bekannt aus Film und Fernsehen',
                    'description' => 'Hat es in sich und ist sehr lecker.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten Shaken und ins Glas geben. Zur Dekoration eine Ananas und eine Kirsche am Glas befestigen.',
                    'is_veggy' => false,
                ],
                [
                    'name' => 'Iced Coffee',
                    'status' => 'published',
                    'punchline' => 'Erfrischender Koffein-Kick',
                    'description' => 'Kalter Kaffee mit Milch und Eiswürfeln.',
                    'difficulty' => 'leicht',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Kaffee brühen, abkühlen lassen, mit Milch servieren.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Mojito',
                    'status' => 'published',
                    'punchline' => 'Kubanischer Klassiker',
                    'description' => 'Rum, Limette, Minze und Soda – perfekt für den Sommer.',
                    'difficulty' => 'mittel',
                    'rating' => 4,
                    'preparation_time' => 10,
                    'preparation_instructions' => 'Minze zerdrücken, Limette auspressen, alles mischen.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Coconut Kiss',
                    'status' => 'published',
                    'punchline' => 'Alkoholfrei und lecker',
                    'description' => 'Ananassaft, Kokossirup und Sahne, getopped mit einem Schuss Grenadine.',
                    'difficulty' => 'einfach',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten in den Shaker geben und shaken.',
                    'is_veggy' => true,
                ],
                [
                    'name' => 'Pina Colada',
                    'status' => 'published',
                    'punchline' => 'Karibisch und lecker',
                    'description' => 'Brauner Rum, weißter Rum, Ananassaft, Kokossirup und Sahne.',
                    'difficulty' => 'einfach',
                    'rating' => 3,
                    'preparation_time' => 5,
                    'preparation_instructions' => 'Alle Zutaten in den Shaker geben und shaken.',
                    'is_veggy' => true,
                ],
            ],
        ];

        foreach ($recipesByCategory as $slug => $recipes) {
            $category = $categories[$slug] ?? null;

            if (!$category) {
                continue;
            }

            foreach ($recipes as $data) {
                Recipe::create(array_merge($data, [
                    'category_id' => $category->id,
                    'user_id' => 1,
                ]));
            }
        }
    }
}
