export enum UNITS {
    SP = 'TL',
    TS = 'EL',
    ML = 'ml',
    CL = 'cl',
    L = 'L',
    GR = 'gr',
    KG = 'kg',
    BT = 'Prise(n)',
    DASH = 'Dash',
    DROP = 'Tropfen',
    PART = 'Teil(e)',
    CUP = 'Tasse(n)',
    PIECE = 'Stück(e)',
    CAN = 'Dose(n)',
    GLASS = 'Glas/Gläser',
    PACKAGE = 'Päckchen',
}
