export enum UNITS {
    SP = 'TL',
    TS = 'EL',
    ML = 'ml',
    CL = 'cl',
    L = 'L',
    GR = 'gr',
    KG = 'kg',
    BT = 'Prise',
    DASH = 'Dash',
    PART = 'Teil(e)',
    CUP = 'Tasse(n)',
    PIECE = 'Stück',
    CAN = 'Dose(n)',
    GLASS = 'Glas',
    PACKAGE = 'Paket(e)',
}
