name: FTPS Test

on:
  push:
    branches: [production]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: ./
        with:
          server: server39.webgo24.de
          username: web176
          password: ${{ secrets.ftp_password }}
          protocol: ftps
